[package]

name = "imap"
version = "1.0.1"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>",
           "Jon Gjengset <jon@thesquareplanet.com>"]
documentation = "https://docs.rs/imap/"
repository = "https://github.com/jonhoo/rust-imap"
homepage = "https://github.com/jonhoo/rust-imap"
description = "IMAP client for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[badges]
travis-ci = { repository = "jonhoo/rust-imap" }
codecov = { repository = "jonhoo/rust-imap", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "jonhoo/rust-imap" }
is-it-maintained-open-issues = { repository = "jonhoo/rust-imap" }

[lib]
name = "imap"
path = "src/lib.rs"

[dependencies]
native-tls = "0.2.2"
regex = "1.0"
bufstream = "0.1"
imap-proto = "0.7"
nom = "4.0"
base64 = "0.10"

[dev-dependencies]
lettre = "0.9"
lettre_email = "0.9"
