[package]
name = "imap"
version = "3.0.0-alpha.2"
authors = ["Jon Gjengset <jon@thesquareplanet.com>",
           "Matt McCoy <mattnenterprise@yahoo.com>"]
documentation = "https://docs.rs/imap/"
repository = "https://github.com/jonhoo/rust-imap"
homepage = "https://github.com/jonhoo/rust-imap"
description = "IMAP client for Rust"
license = "Apache-2.0 OR MIT"
edition = "2018"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[features]
tls = ["native-tls"]
default = ["tls"]

[dependencies]
native-tls = { version = "0.2.2", optional = true }
regex = "1.0"
bufstream = "0.1"
imap-proto = "0.14"
nom = "6.0"
base64 = "0.13"
chrono = "0.4"
lazy_static = "1.4"
linked_hash_set = "0.1"

[dev-dependencies]
lettre = "0.9"
lettre_email = "0.9"
rustls-connector = "0.13.0"

[[example]]
name = "basic"
required-features = ["default"]

[[example]]
name = "gmail_oauth2"
required-features = ["default"]

[[test]]
name = "imap_integration"
required-features = ["default"]
