[package]

name = "imap"
version = "0.2.1"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
documentation = "http://mattnenterprise.github.io/rust-imap"
repository = "https://github.com/mattnenterprise/rust-imap"
homepage = "https://github.com/mattnenterprise/rust-imap"
description = "IMAP client for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"
keywords = ["imap"]

[lib]
name = "imap"
path = "src/lib.rs"

[dependencies]
openssl = "0.8"
regex = "0.2"

[dev-dependencies]
base64 = "0.2"
